config/routes.rb
# coding: UTF-8

Folder::Application.routes.draw do
  root to: 'uploads#new'
  resources :uploads, only: [:index, :new, :create, :show] do
    member do
      get :download
      get :raw
    end
  end
end

app/models/upload.rb
# coding: UTF-8

# Public: An uploaded file and its metadata.
Upload = Struct.new(:id, :filename) do
  # Internal: An Array of file extensions that are considered images.
  IMAGE_EXTENSIONS = %w(jpg jpeg gif png)

  # Internal: The path in which files are stored.
  UPLOAD_DIR = FileUploader.new.store_dir.freeze

  # Public: Returns whether or not the file is an image.
  def image?
    IMAGE_EXTENSIONS.include? File.extname(filename)[1..-1]
  end

  # Public: Returns the path to the file, relative to the `public` directory.
  def path
    "/#{UPLOAD_DIR}/#{filename}"
  end

  def self.find(id)
    file = nil
    FileUtils.chdir(Rails.root.join('public', UPLOAD_DIR)) do
      file = Dir["#{id}.*"].first
    end
    self.new(id, file) if file
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/uploads_controller.rb
# coding: UTF-8

class UploadsController < ApplicationController
  def index
    # TODO
  end

  def show
    # TODO: retrieve metadata like content type and dimensions
    @file = Upload.find(params[:id])
    unless @file
      raise ActionController::RoutingError.new(params[:id])
    end
    if @file.image?
      render 'show_image'
    else
      render 'show_file'
    end
  end

  def raw
    get(params[:id], disposition: :inline)
  rescue ArgumentError => e
    Rails.logger.info "#{self.class.name}#raw: #{e.message}"
    raise ActionController::RoutingError.new(params[:id])
  end

  def download
    get(params[:id], disposition: :attachment)
  rescue ArgumentError => e
    Rails.logger.info "#{self.class.name}#download: #{e.message}"
    raise ActionController::RoutingError.new(params[:id])
  end

  def new
  end

  def create
    # TODO: handle empty file
    uploader = FileUploader.new
    uploader.store!(params[:upload])
    redirect_to upload_path(uploader.folder_id)
  end

  private

  # Internal: Sends the upload to the browser.
  #
  # id      - The upload id.
  # options - A Hash of options given to `send_file`.
  #
  # Raises ArgumentError if the upload is not found.
  def get(id, options = {})
    upload = Upload.find(id)
    unless upload
      raise ArgumentError.new("No upload found for #{id}")
    end
    send_file "public#{upload.path}", options
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/images_helper.rb
# coding: UTF-8

module ImagesHelper
end

app/helpers/uploads_helper.rb
# coding: UTF-8

module UploadsHelper
end

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title Folder
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  %body
    = yield

app/views/uploads/index.html.haml
%h1 Uploads#index
%p Find me in app/views/uploads/index.html.haml

app/views/uploads/new.html.haml
%h1 Upload new file
%section.file.file-new
  = form_tag uploads_path, multipart: true do
    %p
      = label_tag :upload, 'Upload:'
      = file_field_tag :upload
    %p
      = submit_tag 'Upload'

app/views/uploads/show_file.html.haml
%article.file
  %h1= @file.filename
  = link_to 'Raw', raw_upload_path(@file.id)
  = link_to 'Download', download_upload_path(@file.id)

app/views/uploads/show_image.html.haml
%article.file.file-image
  %h1= @file.filename
  - # TODO: display thumbnail version
  = image_tag @file.path
  = link_to 'Full Size', raw_upload_path(@file.id)
  = link_to 'Download', download_upload_path(@file.id)